server:
  port: 8082

spring:
  application:
    name: resource-server
  security:
    oauth2:
      resource-server:
        jwt:
#          This make resource-server the ability to validate the code which comes from authorization-server
          issuer-uri: http://authorization-server:8081
