server:
  port: 8083

spring:
  application.name: gateway-client-server
  cloud:
    gateway:
      routes:
        - id: resources
          uri: http://resource-server:8082/messages
          predicates:
            Path=/messages/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: gateway-client
            client-secret: my-secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://gateway-client-server:8083/login/oauth2/code/{registrationId}"
            scope: openid, message.read
        provider:
          my-provider:
            issuer-uri: http://authorization-server:8081
