version: "3.9"
services:
  postgres:
    container_name: keycloak-demo-db
    image: postgres
    environment:
      POSTGRES_DB: "keycloak-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak-db
      DB_USER: postgres
      DB_PASSWORD: root
      KEYCLOAK_HOSTNAME: keycloak-auth-server
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
