version: "3.9"
services:
  postgres:
    container_name: oauth-demo-db
    image: postgres
    environment:
      POSTGRES_DB: "oauth-demo"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
